# Custom nav
nav:
  title: "Anscor"

favicon: ""

# Custom background
background:
  color: "#eff0f6"
  image: ""

# Social media
social:
  GitHub: https://github.com/anscor

# Custom footer
mail: xlyanscor@outlook.com
copyright: All rights reserved @Anscor

# Custom menu. You can specific the path or the card style (only useful for category page).
# Two kinds of card style: 'project-card', 'article-card',
# Never mind the name.
menu:
  # Project:
  #   path: /categories/Projects
  #   card: project-card
  # Stuffs:
  #   path: /tags/Stuffs
  #   card: article-card
  主页: /
  标签: /tags
  类别: /categories
  归档: /archives
  关于: /about

# Specific default categories or tags of home page.
# Post which belongs to `category` or `tag` and don't belongs to `except_category` or `except_tag` will be filtered.
home:
  # set card style of home page
  # category: Projects
  # tag: 算法
  # except_category: 树
  # except_tag:
  #   - 总结
  #   - css

card_style:
  主页: project-card
  类别: article-card
  标签: article-card
  归档: article-card
  关于: article-card

# category page
category_generator:
  category_per_page: 3
  post_per_category: 3

node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false